webtalk_init -webtalk_dir C:/verilog files/times_gate_operated/times_gate_operated.sim/sim_1/behav/xsim/xsim.dir/testbench_times_gate_operated_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Sep 26 16:43:35 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2674993d-b5dc-4f1f-81c1-e964b01fdec3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "458c9d1226cc4141a561bca7acb16499" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6384_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3581343441 -regid "" -xml C:/verilog files/times_gate_operated/times_gate_operated.sim/sim_1/behav/xsim/xsim.dir/testbench_times_gate_operated_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/verilog files/times_gate_operated/times_gate_operated.sim/sim_1/behav/xsim/xsim.dir/testbench_times_gate_operated_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/verilog files/times_gate_operated/times_gate_operated.sim/sim_1/behav/xsim/xsim.dir/testbench_times_gate_operated_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
